### PR TITLE
WinrtServer: Also copy missing base.h

### PR DESCRIPTION
**Pull request by forderud**
Transitive dependency by WinrtServer.h (include in line number 6).

### CODE REVIEW

**Comment by forderud** [comment]
@jogerh Would you mind taking a look at this?

This is preparation work towards simplifying the client code that further that I want to introduce in a later PR.

**Comment by jogerh** [comment]
Thank you @forderud. But please have a look at #41. I think maybe we have to copy all the files from the winrt as you first suggested, since our new 'winrt' folder from the WinrtServer replaces the winrt server provided by the Windows SDK. Or do I miss something?

**Comment by forderud** [comment]
> Thank you @forderud. But please have a look at #41. I think maybe we have to copy all the files from the winrt as you first suggested, since our new 'winrt' folder from the WinrtServer replaces the winrt server provided by the Windows SDK. Or do I miss something?

Might very well be the case. I honestly don't have an overview of what is considered "best practice" in this area.

**Comment by jogerh** [comment]
OK. Let's figure this out as we go.

**Pull request merged**
